#pragma once

#define AUTO_SHIFT_MODIFIERS
#define AUTO_SHIFT_NO_AUTO_REPEAT
#define NO_AUTO_SHIFT_ALPHA
#undef AUTO_SHIFT_TIMEOUT
#define AUTO_SHIFT_TIMEOUT 150

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 2000

#define ONESHOT_TIMEOUT 2000

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#undef HOLD_ON_OTHER_KEY_PRESS
