#pragma once

#define AUTO_SHIFT_MODIFIERS
#define AUTO_SHIFT_NO_AUTO_REPEAT
#define NO_AUTO_SHIFT_ALPHA
#undef AUTO_SHIFT_TIMEOUT
#define AUTO_SHIFT_TIMEOUT 150

#define GRAVE_ESC_GUI_OVERRIDE
#define GRAVE_ESC_CTRL_OVERRIDE

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 2000

#define ONESHOT_TIMEOUT 2000

